name: task
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  build_runner:
  flutter_gen_runner:
  firebase_core:
  firebase_auth:
  firebase_storage:
  firebase_cloud_firestore:
  cloud_firestore: ^5.4.2
  equatable:
  bloc:
  flutter_bloc:
  get_it:
  flutter_slidable: ^3.1.1
  go_router: ^14.2.7
  date_picker_timeline: ^1.2.6
  animated_bottom_navigation_bar:
  easy_localization:
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  fonts:
   - family: Poppins
     fonts:
         - asset: assets/font/poppins-bold.ttf
           weight: 700
         - asset: assets/font/poppins-medium.ttf
           weight: 500
         - asset: assets/font/poppins-regular.ttf
           weight: 400

  assets:
    - assets/images/
    - assets/font/
    - assets/translations/
    - sec.env



